### PR TITLE
Add support for annotations in visualization

### PR DESCRIPTION
**Pull request by anishathalye**
See documentation for `LinearizationInfo.AddAnnotations` and the new `Annotation` type.

Example:

<a href="https://anishathalye.github.io/porcupine/demo-annotations.html">Visualization demo</a>

[[view interactive version]](https://anishathalye.github.io/porcupine/demo-annotations.html)

### CODE REVIEW

**Comment by serathius** [comment]
Awesome! This does exactly what I had in mind.

**Comment by anishathalye** [comment]
Please let me know when you get a chance to test this — I would like to confirm that the API works for you before merging/releasing this addition to the public API of Porcupine.

**Comment by serathius** [comment]
Sorry, I didn't know you wanted for etcd testing the feature, I'm pretty busy this week, but maybe someone else from etcd community can help.

**Comment by anishathalye** [comment]
There's no rush on my end, happy to hear your feedback whenever you have time

**Comment by anishathalye** [comment]
Squashed and merged in 12c3848.

**Pull request closed without merging**
